### ISSUE TITLE
Finer control over coverage

### ISSUE THREAD

**Issue by nirajmehta96** [mbhall88/rasusa#19]
Hi,

Any float input to coverage is automatically rounded down to the lower integer. We are testing in a coverage regime where we want to inspect the finer effects of coverage. Is it possible to have a coverage of exactly (or approximately exactly) what we input into -c?

Thanks!

**Comment by mbhall88** [comment]
That should be fine. I will just have to tweak some types. Give me a few days before I can get around to doing this.

**Comment by mbhall88** [comment]
Version 0.3.0 should now treat coverage as a float. Let me know if you have any problems.
