### ISSUE TITLE
Suggestion: Raise warning when desired level of coverage is not possible

### ISSUE THREAD

**Issue by k3yavi** [mbhall88/rasusa#36]
Hi, 

This is with respect to https://github.com/openjournals/joss-reviews/issues/3941 .

The tool works perfectly for the designed use case. However I think it'd be great to raise a warning when the desired level of coverage is not possible, for example when the fraction of reads to the size of the genome is not large enough.

**Comment by mbhall88** [comment]
Thanks @k3yavi, good suggestion. Done in https://github.com/mbhall88/rasusa/commit/31bb0bfa375ef2f65b27b431901834927e8e7510
