### ISSUE TITLE
Does rasusa outputs reads that still cover the entire original genome?

### ISSUE THREAD

**Issue by MostafaYA** [mbhall88/rasusa#56]
Hi, 
When using `rasusa`  for downsampling, do we get reads that still cover the whole genome but with a reduced depth, or is it possible that the reads are only sampled from certain regions (i.e. there is no guarantee that the original genome is well represented in the output)? 
Thanks

**Comment by mbhall88** [comment]
Hi @MostafaYA. Rasusa takes a random subsample of the reads, so there is no guarentee of what parts of the genome will be sampled - as Rasusa knows nothing about whether the reads align to on the genome. 

If you want to subsample and ensure coverage across the genome I'd suggest taking a look at [this suggestion](https://github.com/mbhall88/rasusa/issues/17#issuecomment-708165373).
