### ISSUE TITLE
Random sampling based on bases for the metagenomic dataset

### ISSUE THREAD

**Issue by AnupamGautam** [mbhall88/rasusa#59]
Dear Developers,

I am working on a comparative study, for which we are using short-read and long-reads metagenomic samples.  We want to subsample our long reads dataset based on bases, For Eg, if our randomly sub-sampled short read metagenomic sample has 10,000 reads which make up 1,500,000 bases in total, we want to subsample our long read dataset to 1,500,000 bases. For short read, we used reformat.sh (to randomly subsample reads).

I  searched tools for subsampling long reads to achieve the required bases. but none of them use random sampling, I might have missed some tools which can do it.

My question is will it be possible to do it by using Rasusa for the metagenomic dataset?

Thanks,
Anupam

**Comment by mbhall88** [comment]
Yes, you can subsample to a given number of bases. Please see the [docs section describing this option](https://github.com/mbhall88/rasusa#-b---bases).
