### ISSUE TITLE
Error: unable to gather read lengths for the first input file

### ISSUE THREAD

**Issue by npdungca** [mbhall88/rasusa#65]
Hi. I'm trying to subsample by depth and I'm getting this error:

./rasusa -i barcode05_duplex.fastq.gz --coverage 400 --genome-size 243724 -s 100 -o BC05_400x.fq.gz
[2023-10-02][13:20:16][rasusa][INFO] Target number of bases to subsample to is: 97489600
[2023-10-02][13:20:16][rasusa][INFO] Gathering read lengths...
Error: unable to gather read lengths for the first input file

Caused by:
    0: Failed to parse record
    1: Sequence length is 373 but quality length is 120 (record '5ad0b9e9-94a7-477c-b47f-0963e639d159' at line 1544857)

Thank you for your help.

**Comment by mbhall88** [comment]
Sounds like your input fastq might have an invalid record. You can confirm this with [`seqkit`](https://github.com/shenwei356/seqkit) by running `seqkit seq barcode05_duplex.fastq.gz > /dev/null`

**Comment by npdungca** [comment]
Got it. It seems that the last line got trucated. Thank you so much for patiently answering my queries.
![Screenshot from 2023-10-22 16-28-00](https://github.com/mbhall88/rasusa/assets/89509602/9157d624-65d3-42e8-84f6-63fc780b68ba)

**Comment by npdungca** [comment]
Got it. It seems that the last line got trucated. Thank you so much for patiently answering my queries.
![Screenshot from 2023-10-22 16-28-00](https://github.com/mbhall88/rasusa/assets/89509602/e4b9e1b2-88fa-4c1e-b441-0719af936963)
