### ISSUE TITLE
does downsampling with rasusa preserve regions of copy number variation?

### ISSUE THREAD

**Issue by eesiribloom** [mbhall88/rasusa#75]
I am interested in using rasusa to randomly downsample my alignment files (BAM) to a specified mean whole genome coverage. My question is if this will preserve regions of copy number amplification within the file?

**Comment by mbhall88** [comment]
Hi @eesiribloom. What it does is cap every position at a maximum of N. So if you set a downsample depth of 100x and you have a region with copy number of say 200x, that region will be downsampled to 100x. If you have a region of 50x, there won't be any downsampling of it.

Does this answer your question?

**Comment by eesiribloom** [comment]
Yes it does thank you. I think in this case it wouldn't preserve regions of copy number amplification as these are regions of high coverage.
